### ISSUE TITLE
change , to | on dump

### ISSUE THREAD

**Issue by mrfragger** [Subat-Ahsan/PDF_TOC_Creator#1]
65             outline_string = '>'*i[0] + i[1]+','+str(i[2]) +'\n'
change to 
65            outline_string = '>'*i[0] + i[1]+'|'+str(i[2]) +'\n'

thanks for this script..seems easy to use and straight forward

still pdf-toc-gen seems to be able to keep vertical position in page ..maybe even cpdf...most however do not though.  

Meaning if heading is like 30% down the page the bookmark opens precisely to that location.

**Comment by Subat-Ahsan** [comment]
Thanks for the change.

For maintaining the vertical position, I think it links to the specific heading. I don't know how that would work with scanned pdfs.

**Comment by mrfragger** [comment]
If you want to include the vertical position in a page for each heading, use the -v flag

 pdftocgen -v doc.pdf < rcp.toml

"Level 1 heading 1" 1 306.947998046875
    "Level 2 heading 1" 1 586.3488159179688
        "Level 3 heading 1" 2 586.5888061523438
        "Level 3 heading 2" 3 155.66879272460938
    "Level 2 heading 2" 4 435.8687744140625
"Level 1 heading 2" 5 380.78875732421875

pdftocio can understand the vertical position in the output to generate table of contents entries that link to the exact position of the heading, instead of the top of the page.

yea only one paid app I know does vertical position and only free (open-source) one I know of is pdftocgen

yea PDF needs to be OCR'ed for it to detect same font, font size and hope they are uniform throughout the PDF.  If not it's a disaster.  One problem though if you decide to crop (real crop not just adjusting margins) then the location remains to the original uncropped version of the page.  I assume this is due to the page info remaining and not getting adjusted when PDF is cropped.  

Anyway I believe your PDF_TOC_Creator is the easiest to use and best choice for the vast majority of users who don't need vertical position.
